apiVersion: v1
kind: Service
metadata:
  labels:
    run: flask10-application
  name: flask10-application
spec:
  ports:
  - name: http
    port: 5011
    protocol: TCP
    targetPort: 5000
  selector:
    run: flask10-application
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask10-application
spec:
  replicas: 2
  selector:
    matchLabels:
      run: flask10-application
  template:
    metadata:
      labels:
        run: flask10-application
    spec:
      containers:
      - image: adminguytesting/flask10:2.0.0
        imagePullPolicy: Always
        name: flask10-application
        ports:
        - containerPort: 5000
