apiVersion: v1
kind: Service
metadata:
    labels:
        run: flask10
    name: flask10
spec:
    ports:
    - name: http
      port: 5011
      protocol: TCP
      targetPort: 5000
    selector:
        run: flask10
    type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: flask10
spec:
    replicas: 1
    selector:
        matchLabels:
            run: flask10-application
    template:
        metadata:
            labels:
                run: flask10application
        spec:
            containers:
            - name: flask10-application
              image: adminguytesting/flask10:1.0.0
              ports:
                  - containerPort: 5000
              imagePullPolicy: Always